FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    iptables \
    libnetfilter-queue-dev \
    gcc \
    python3-dev \
    iproute2 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install scapy NetfilterQueue

CMD ["tail", "-f", "/dev/null"]